version: '3'

services:
    mongo:
      image: mongo
      networks:
        - mynet
      ports:
        - "27017:27017"

    results:
      build: ./service/results
      image: pclub/puppy-love:results
      env_file:
        - .backend.env
      links:
        - mongo
      networks:
        - mynet

    signup:
      build: ./service/signup
      image: pclub/puppy-love:signup
      env_file:
        - .backend.env
        - .mail.env
      ports:
        - "3001:3001"
      links:
        - mongo
      networks:
        - mynet

    backend:
      build: .
      image: pclub/puppy-love:backend
      env_file:
        - .backend.env
#        - .pass.env
      ports:
        - "34770:3000"
      links:
        - mongo
        - signup
      networks:
        - mynet

    frontend:
      build: ./frontend
      image: pclub/puppy-love:frontend
      ports:
        - "34771:80"
      networks:
        - mynet
    
    nginx:
      build: ./service/nginx
      image: pclub/puppy-love:nginx
      ports:
        - "80:80"
      networks:
        - mynet
      depends_on:
        - "backend"
        - "frontend"

networks:
  mynet:
